# -----------------------------------------------
# Name:  Aryan Rusia
# SID:   1669003
# CCID:  rusia
# CMPUT 275 Winter 2022
# Weekly EXercise 7 - Divide and Conquer
# ----------------------------------------------

CC = g++
PROGRAM = we7_solution

we7_solution: climbing.o
		$(CC) -o we7_solution climbing.o


climbing.o: climbing.cpp
		$(CC) -c climbing.cpp

clean:
		@rm $(PROGRAM) climbing.o
